Fix for trades reducing coin quantities
ccxt/binance-trade-bot pull request #140
Opened 2021-02-27 08:59 UTC by johannes-peeters

Base a trade on a single pull of ticker information. Re-querying the API added latency and if the price increased between the queries the actual quantity traded could be lower than the previous holding

2021-02-27 09:14 UTC, rel-s commented
I like it. Will test soon.

2021-02-27 10:32 UTC, porter707 commented
I'm running this now will update when it trades

2021-02-27 10:33 UTC, porter707 commented on binance_api_manager.py
> +                    price=self.from_coin_price,
the self here is not needed

2021-02-27 10:40 UTC, darthvader666uk commented
Im also running this now and will report back once trades are done :)

2021-02-27 11:28 UTC, porter707 commented on binance_api_manager.py
> +        from_coin_price = get_market_ticker_price_from_list(all_tickers, alt_symbol + crypto_symbol)
This function doesn't exist in this file

2021-02-27 11:39 UTC, johannes-peeters commented on binance_api_manager.py
> +        from_coin_price = get_market_ticker_price_from_list(all_tickers, alt_symbol + crypto_symbol)
I added the function in the binance_api_manager as a quick fix. Please test. When integrating we should clean this up.

2021-02-27 11:45 UTC, porter707 commented on binance_api_manager.py
> +        from_coin_price = get_market_ticker_price_from_list(all_tickers, alt_symbol + crypto_symbol)
You also need to add the "first" function that is called inside get_market_ticker_price_from_list function

I think the best way to clean it up would be using the code from j-waters refactor branch

https://github.com/j-waters/binance-trade-bot/blob/refactor/binance_trade_bot/utils.py

2021-02-27 11:52 UTC, johannes-peeters commented on binance_api_manager.py
> +        from_coin_price = get_market_ticker_price_from_list(all_tickers, alt_symbol + crypto_symbol)
Added. I will work on j-waters code next

2021-02-27 13:56 UTC, porter707 commented on binance_api_manager.py
> +        from_coin_price = get_market_ticker_price_from_list(all_tickers, alt_symbol + crypto_symbol)
Another issue both the methods added are missing their self param as the first argument

2021-02-27 15:17 UTC, johannes-peeters commented on binance_api_manager.py
> +        from_coin_price = get_market_ticker_price_from_list(all_tickers, alt_symbol + crypto_symbol)
Sorry for this. I had my changes based on the code prior to the Binance api abstraction. Likely why my bot stopped working this afternoon. Will fix once behind device again

2021-02-27 17:24 UTC, rel-s approved these changes

2021-02-27 17:25 UTC, rel-s commented
Code looks good to me, just waiting for some tests to complete and we can move forward with this soon; probably after merging #107 though.

2021-02-27 17:27 UTC, j-waters commented on binance_api_manager.py
> +        from_coin_price = get_market_ticker_price_from_list(all_tickers, alt_symbol + crypto_symbol)
I would personally just move them to a new `utils.py` file since they don't need to reference the manager instance. Or at least make them static

2021-02-27 17:31 UTC, j-waters commented
Don't think it'll conflict with anything from #107 so it probably doesn't matter. Has the above issue been fixed?

2021-02-27 17:33 UTC, rel-s commented on binance_api_manager.py
> +        from_coin_price = get_market_ticker_price_from_list(all_tickers, alt_symbol + crypto_symbol)
@j-waters Your suggestion makes sense, but I see this already exists in your new PR #148. So perhaps it would be best to leave this out of `utils.py` for now, and we'll get to modularising the whole project soon.

2021-02-27 17:33 UTC, darthvader666uk commented
> 
> 
> Code looks good to me, just waiting for some tests to complete and we can move forward with this soon; probably after merging #107 though.

still running some test as there was an issue so i had to pull down the latest changes.

Waiting for a trade to confirm

2021-02-27 17:45 UTC, j-waters commented on binance_api_manager.py
> +        from_coin_price = get_market_ticker_price_from_list(all_tickers, alt_symbol + crypto_symbol)
@rel-s That's fair, it's not that big of a deal

2021-02-27 17:49 UTC, darthvader666uk commented
Alright I got this error:

```
2021-02-27 17:44:00,142 - crypto_trader_logger - ERROR - Error while updating value history...
Traceback (most recent call last):
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Darth\Documents\work\binance-trade-bot\scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\schedule\__init__.py", line 147, in _run_job
    ret = job.run()
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\schedule\__init__.py", line 491, in run
    ret = self.job_func()
  File "C:\Users\Darth\Documents\work\binance-trade-bot\crypto_trading.py", line 193, in update_values
    balance = client.get_currency_balance(coin.symbol)
  File "C:\Users\Darth\Documents\work\binance-trade-bot\binance_api_manager.py", line 46, in get_currency_balance
    for currency_balance in self.BinanceClient.get_account()[u"balances"]:
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 1767, in get_account
    return self._get('account', True, data=params)
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 196, in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

2021-02-27 17:44:39,015 - crypto_trader_logger - ERROR - Error while scouting...
Traceback (most recent call last):
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Darth\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinE [...]

2021-02-27 18:01 UTC, j-waters commented
@darthvader666uk that doesn't look like it should be related to this PR although I may be wrong. The PR doesn't work for me at the moment but for a completely different issue

2021-02-27 18:15 UTC, darthvader666uk commented
> 
> 
> @darthvader666uk that doesn't look like it should be related to this PR although I may be wrong. The PR doesn't work for me at the moment but for a completely different issue

I got a feeling your right but at the same time, im not sure!  just reset the bot and a go again, see if it can be picked up :)

2021-02-27 18:23 UTC, rel-s requested changes
Add the "self" argument to both new functions in `binance_api_manager.py` please

2021-02-27 19:10 UTC, darthvader666uk commented
I ran it again, yep got this:

```
2021-02-27 19:09:41,687 - crypto_trader_logger - INFO - Balance is 0.36963702
2021-02-27 19:09:41,925 - crypto_trader_logger - INFO - order
2021-02-27 19:09:41,925 - crypto_trader_logger - INFO - {'symbol': 'ETHUSDT', 'orderId': 3172960123, 'orderListId': -1, 'clientOrderId': '54xSOtznL5aaZEvKw8OeRs', 'transactTime': 1614452982614, 'price': '0.00000000', 'origQty': '0.36963000', 'executedQty': '0.36963000', 'cummulativeQuoteQty': '555.78306060', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'SELL', 'fills': [{'price': '1503.62000000', 'qty': '0.36963000', 'commission': '0.55578306', 'commissionAsset': 'USDT', 'tradeId': 311444883}]}
2021-02-27 19:09:41,937 - crypto_trader_logger - INFO - Waiting for Binance
2021-02-27 19:09:50,188 - crypto_trader_logger - INFO - {'symbol': 'ETHUSDT', 'orderId': 3172960123, 'orderListId': -1, 'clientOrderId': '54xSOtznL5aaZEvKw8OeRs', 'price': '0.00000000', 'origQty': '0.36963000', 'executedQty': '0.36963000', 'cummulativeQuoteQty': '555.78306060', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'MARKET', 'side': 'SELL', 'stopPrice': '0.00000000', 'icebergQty': '0.00000000', 'time': 1614452982614, 'updateTime': 1614452982614, 'isWorking': True, 'origQuoteOrderQty': '0.00000000'}
2021-02-27 19:09:50,433 - crypto_trader_logger - INFO - Sold ETH
2021-02-27 19:09:52,419 - crypto_trader_logger - INFO - Failed to Buy/Sell. Trying Again.
2021-02-27 19:09:52,419 - crypto_trader_logger - INFO - name 'get_market_ticker_price_from_list' is not defined
2021-02-27 19:09:53,399 - crypto_trader_logger - INFO - Failed to Buy/Sell. Trying Again.
2021-02-27 19:09:54,158 - crypto_trader_logger - INFO - Failed to Buy/Sell. Trying Again.
2021-02-27 19:09:55,120 - crypto_trader_logger - INFO - Failed to Buy/Sell. Trying Again.
2021-02-27 19:09:56,082 - crypto_trader_logger - INFO - Failed to Buy/Sell. Trying Again.
2021-02-27 19:09:56,839 - crypto_trader_logger - INFO - Failed to Buy/Sell. Trying Again.
2021-02-27 19:09:57,595 - crypto_trader_logger - INFO - Failed to Buy/Sell. Trying Again.
```

2021-02-27 19:15 UTC, rel-s commented
@darthvader666uk This might be because of the issue we mentioned here... I didn't get a trade yet, but I added the `self` argument to the functions and I'll check if it works.

2021-02-27 19:19 UTC, darthvader666uk commented
> 
> 
> @darthvader666uk This might be because of the issue we mentioned here... I didn't get a trade yet, but I added the `self` argument to the functions and I'll check if it works.

cool i thought so but thought to give the log too, just to help (if i could)

If you need me to have a test once you have committed the changes let me know, ive paused the bot for now

2021-02-27 22:49 UTC, johannes-peeters commented
> Add the "self" argument to both new functions in `binance_api_manager.py` please

Done

2021-02-27 22:50 UTC, rel-s approved these changes

2021-02-27 23:07 UTC, porter707 commented
This is working great for me I've been running this all day (with the fixes) and it's made a bunch of positive trades

2021-02-27 23:09 UTC, rel-s commented
@porter707 That's good to hear! I'm still waiting for some transactions in my test bot, as soon as I can confirm we'll merge this.

2021-02-27 23:11 UTC, johannes-peeters commented
There are a few other API calls I'd like to remove to reduce the latency even further. I'll make a separate PR for these changes, so this one can already been merged once validated.

2021-02-28 00:56 UTC, darthvader666uk commented
Re-based and going to re-test, shall report back with results :)

2021-02-28 07:42 UTC, rel-s commented
@johannes-peeters way to go man, more optimizations in this direction could have a real impact on bot stability. Merging.

2021-02-28 07:44 UTC, merged

2021-02-28 09:59 UTC, darthvader666uk commented
I know this is merged but the bot made some trades last night.  It made 3 after the rebase and all in the positives, looks good to me!