✨ Environment Variable Support
ccxt/binance-trade-bot pull request #143
Opened 2021-02-27 11:25 UTC by segersniels

### Added
- Allows user to provide `user.cfg` settings by configuring environment variables

```
SUPPORTED_COINS: "XLM TRX ICX EOS IOTA ONT QTUM ETC ADA XMR DASH NEO ATOM DOGE VET BAT OMG BTT"
BRIDGE_CURRENCY: USDT
CURRENT_COIN:
API_KEY:
API_SECRET_KEY:
```

2021-02-28 11:25 UTC, segersniels commented
Still troubleshooting some minor issues.

2021-03-04 05:41 UTC, edeng23 commented
Can you please rebase? The config code was moved to a separate file in #148. Thanks!

2021-03-04 08:39 UTC, segersniels commented
> Can you please rebase? The config code was moved to a separate file in #148. Thanks!

🚀

2021-03-04 10:20 UTC, edeng23 requested changes
You must take into consideration the scenario in which a user (me, for example) does not use environment variables. I'd really appreciate if you can take the time to run the code on a config file. Thanks :)

2021-03-04 10:20 UTC, edeng23 commented on README.md
> +Most of the options provided in `user.cfg` can also be configured using environment variables.
Why **most** and not **all**?  Why isn't tld in your list?

2021-03-04 10:20 UTC, edeng23 commented on binance_trade_bot/config.py
> +        self.SUPPORTED_COIN_LIST = os.environ.get("SUPPORTED_COIN_LIST").split() or []
This won't work for people not using environment variables. get() will return Nonetype object, which you cannot split, resulting in an Attribute Error.

2021-03-04 10:41 UTC, segersniels commented on README.md
> +Most of the options provided in `user.cfg` can also be configured using environment variables.
Will add all supported ENV vars to the list. It's a bit outdated

2021-03-04 11:07 UTC, segersniels commented
> You must take into consideration the scenario in which a user (me, for example) does not use environment variables. I'd really appreciate if you can take the time to run the code on a config file. Thanks :)

Converted my own running bot to run against config files instead of env vars using the following minimal setup:

### `docker-compose.yml`
```yaml
version: "3"
  
services:
  binance:
    image: segersniels/binance-trade-bot:latest
      - /foo/binance/user.cfg:/app/user.cfg
      - /foo/binance/supported_coin_list:/app/supported_coin_list
    restart: always
```

### Output

```bash                                                                                                                                                                                                                                                        
$ docker logs   
2021-03-04 11:02:32,267 - crypto_trader_logger - INFO - Starting
2021-03-04 11:02:32,868 - crypto_trader_logger - INFO - Creating database schema if it doesn't already exist
                                                                                                                                                                                                                                                        
$ cat /app/user.cfg                  
[binance_user_config]
api_key=
api_secret_key=
current_coin=
bridge=USDT
tld=com
hourToKeepScoutHistory=1
scout_transaction_fee=0.001
scout_multiplier=5
scout_sleep_time=5
                                                                                                                                                                                                                                                    
$ cat /app/supported_coin_list
BTC
ETH
ADA
BNB
LTC
XMR
XLM
ATOM
EOS
TRX
IOTA
VET
NEO
DASH 
ETC 
NANO 
ICX 
SUSHI 
ALGO 
UNI 
CAKE
```

2021-03-04 15:37 UTC, edeng23 approved these changes

2021-03-04 15:38 UTC, merged