stack scout history before writing to db
ccxt/binance-trade-bot pull request #189
Opened 2021-03-08 19:17 UTC by Pekafu

Stacking seems quite efficient.

> 2021-03-08 21:04:21,127 - crypto_trader_logger - INFO - Appending pair ADAXLM to stack.
> 2021-03-08 21:04:21,127 - crypto_trader_logger - INFO - Appending pair ADATRX to stack.
> 2021-03-08 21:04:21,128 - crypto_trader_logger - INFO - Appending pair ADAICX to stack.
> 2021-03-08 21:04:21,128 - crypto_trader_logger - INFO - Appending pair ADAEOS to stack.
> 2021-03-08 21:04:21,128 - crypto_trader_logger - INFO - Appending pair ADAIOTA to stack.
> 2021-03-08 21:04:21,129 - crypto_trader_logger - INFO - Appending pair ADAONT to stack.
> 2021-03-08 21:04:21,129 - crypto_trader_logger - INFO - Appending pair ADAQTUM to stack.
> 2021-03-08 21:04:21,130 - crypto_trader_logger - INFO - Appending pair ADAETC to stack.
> 2021-03-08 21:04:21,130 - crypto_trader_logger - INFO - Appending pair ADAXMR to stack.
> 2021-03-08 21:04:21,130 - crypto_trader_logger - INFO - Appending pair ADADASH to stack.
> 2021-03-08 21:04:21,131 - crypto_trader_logger - INFO - Appending pair ADANEO to stack.
> 2021-03-08 21:04:21,131 - crypto_trader_logger - INFO - Appending pair ADAATOM to stack.
> 2021-03-08 21:04:21,131 - crypto_trader_logger - INFO - Appending pair ADADOGE to stack.
> 2021-03-08 21:04:21,132 - crypto_trader_logger - INFO - Appending pair ADAVET to stack.
> 2021-03-08 21:04:21,132 - crypto_trader_logger - INFO - Appending pair ADABAT to stack.
> 2021-03-08 21:04:21,132 - crypto_trader_logger - INFO - Appending pair ADAOMG to stack.
> 2021-03-08 21:04:21,133 - crypto_trader_logger - INFO - Appending pair ADABTT to stack.
> 2021-03-08 21:04:21,133 - crypto_trader_logger - INFO - Writing scout stack to db.
> 2021-03-08 21:04:23,432 - crypto_trader_logger - INFO - All scout info written.

2021-03-08 19:24 UTC, Pekafu commented
Relates to #182

2021-03-09 03:03 UTC, s0undt3ch requested changes

2021-03-09 03:03 UTC, s0undt3ch commented on binance_trade_bot/auto_trader.py
> +        if(len(scout_stack) > 0):
```suggestion
        if scout_stack:
```
This is enough.

2021-03-09 10:28 UTC, j-waters requested changes
This is a good idea, thanks for implementing.

My only thought is if we could come up with a more general solution, but that's probably more effort than it'd be worth

2021-03-09 10:28 UTC, j-waters commented on binance_trade_bot/database.py
> +        bulk_data = []
```suggestion
        bulk_data = list(model.info() for model in models)
```

Just how I would do it feel free to ignore!

2021-03-09 10:28 UTC, j-waters commented on binance_trade_bot/database.py
> +                sh = ScoutHistory(pair, sh_temp.target_ratio, sh_temp.current_coin_price, sh_temp.other_coin_price)
Is there a reason we're creating a new object here? I'm sure there is because SQLAlchemy can sometimes be tricky but if there's another way we should do that.

```suggestion
                session.add(sh_temp)
```

Does that not work? What if you merged it first and then did that?

2021-03-09 10:28 UTC, j-waters commented on binance_trade_bot/database.py
> +        self.socketio_client.emit('bulk_save_objects', {
```suggestion
        self.socketio_client.emit('update_bulk', {
```

To keep in line with the other emitter

2021-03-09 10:28 UTC, j-waters commented on binance_trade_bot/database.py
> +    def log_scout_stack(self, sh_stack):
```suggestion
    def log_scout_stack(self, sh_stack: List[ScoutHistory]):
```

2021-03-09 10:45 UTC, Pekafu commented on binance_trade_bot/database.py
> +        bulk_data = []
this looks lovely, will definitely change.

2021-03-09 10:47 UTC, Pekafu commented on binance_trade_bot/database.py
> +                sh = ScoutHistory(pair, sh_temp.target_ratio, sh_temp.current_coin_price, sh_temp.other_coin_price)
I was basically mimicing the old implementation and since I'm not exactly sure what that session.merge() does I left it as it is. Checking through that pair might not be needed, since ScoutHistory shouldn't exist without a pair since we ain't updating pairs on the fly.

2021-03-09 11:12 UTC, Pekafu commented on binance_trade_bot/database.py
> +                sh = ScoutHistory(pair, sh_temp.target_ratio, sh_temp.current_coin_price, sh_temp.other_coin_price)
> 
> 
> This is a good idea, thanks for implementing.
> 
> My only thought is if we could come up with a more general solution, but that's probably more effort than it'd be worth
> 
> Also do you have a ballpark on how much time this saves? Just so we don't overcomplicate things for no reason!

I tested it with stacking and running stack in a loop through the old log_scout() and it took more than a minute, now it goes below 3sec, still it should be possible to get it below 1sec.

2021-03-09 11:46 UTC, j-waters commented on binance_trade_bot/database.py
> +                sh = ScoutHistory(pair, sh_temp.target_ratio, sh_temp.current_coin_price, sh_temp.other_coin_price)
`session.merge` takes an object that was created in another database session, refreshes it, and links it with the current session. We have to do this with pairs since they're created in another session.

You could do this:
```suggestion
                sh = session.merge(sh_temp)
```

and it might automatically merge the pair for you, I'm not sure. If that doesn't work, try:
```suggestion
                pair = session.merge(sh_temp.pair)
                sh_temp.pair = pair
```
Something like that? I can test it myself later if needs be

2021-03-09 11:47 UTC, j-waters commented on binance_trade_bot/database.py
> +                sh = ScoutHistory(pair, sh_temp.target_ratio, sh_temp.current_coin_price, sh_temp.other_coin_price)
Also don't know why it took more than a minute originally! That's a good speed increase

2021-03-09 16:11 UTC, Pekafu commented on binance_trade_bot/database.py
> +                sh = ScoutHistory(pair, sh_temp.target_ratio, sh_temp.current_coin_price, sh_temp.other_coin_price)
I don't have time to test in within next couple of days, so go ahead =)

2021-03-11 12:50 UTC, rayures commented
forked and merged this one. 
Works great. time between jump notification to buy order went from 50-ish seconds to 5 seconds.

2021-03-14 14:51 UTC, alienfrenZyNo1 commented
I've implemented this and being running it the last few days. It hasn't broken anything. I have noticed less buy limit misses but it still happens. I like this PR though, understandable and focused on one thing!

2021-03-15 07:10 UTC, rel-s commented on binance_trade_bot/database.py
> +                sh = ScoutHistory(pair, sh_temp.target_ratio, sh_temp.current_coin_price, sh_temp.other_coin_price)
Is this resolved? Does @j-waters modification work?

2021-03-15 12:18 UTC, j-waters commented on binance_trade_bot/database.py
> +                sh = ScoutHistory(pair, sh_temp.target_ratio, sh_temp.current_coin_price, sh_temp.other_coin_price)
I never ended up testing it, I can get round to it though

2021-03-15 13:37 UTC, rayures commented on binance_trade_bot/database.py
> +                sh = ScoutHistory(pair, sh_temp.target_ratio, sh_temp.current_coin_price, sh_temp.other_coin_price)
running it for a couple of days. works fine.

2021-03-18 21:45 UTC, Pekafu commented on .pylintrc
> +ignored-classes=optparse.Values,thread._local,_thread._local,query
couldn't get pre-commit hooks to work without these.

2021-03-18 21:55 UTC, Pekafu commented on binance_trade_bot/database.py
> +    def log_scout_stack(self, sh_stack: List[ScoutHistory]):
with this version it seems to be working within 3secs, I don't currently have a lot of pairs though
> 48:20,989 - crypto_trading_logger - INFO - started stacking
> 48:23,293 - crypto_trading_logger - INFO - stacking rdy
> 48:28,633 - crypto_trading_logger - INFO - started stacking
> 48:30,941 - crypto_trading_logger - INFO - stacking rdy                           
> 48:36,271 - crypto_trading_logger - INFO - started stacking
> 48:38,579 - crypto_trading_logger - INFO - stacking rdy

2021-05-11 15:22 UTC, rel-s approved these changes

2026-07-18 18:36 UTC, closed without merging