Add initial implementation of websockets for getting all mark prices
ccxt/binance-trade-bot pull request #205
Opened 2021-03-14 19:42 UTC by ryansonshine

This change implements the binance websocket client as a quick patch for `get_all_market_tickers` to help with API rate limits.

I probably won't have time to do any more work on this until next weekend so if anyone would like to pick it up I have a list of items I was planning, but didn't have time to do.

- [ ] Implement error handling on message processing callback
- [ ] Implement re-connection logic (websockets will be disconnected after 24 hours)

Fixes #118

2021-03-14 20:27 UTC, j-waters commented on binance_trade_bot/database.py
> +        self.engine = create_engine(uri + "?check_same_thread=False")
https://github.com/edeng23/binance-trade-bot/pull/195/files#diff-0cafd665e7243ffb750d9b2c257d2b3b5673a80451c85d6eacef37e5620f91bcR22

2021-03-14 20:42 UTC, j-waters requested changes
This is good, maybe we'll be able to remove the whole `get_all_market_tickers` and `get_market_ticker_price_from_list` and just replace it with a straight function call

2021-03-14 20:42 UTC, j-waters commented on binance_trade_bot/binance_api_manager.py
> +        return self.cache
Maybe a more specific name? `ticker_prices`?

2021-03-14 20:42 UTC, j-waters commented on binance_trade_bot/crypto_trading.py
> +    while len(manager.cache) == 0:
I'd move this within `get_all_market_tickers`

2021-03-14 22:43 UTC, Pekafu commented on binance_trade_bot/binance_api_manager.py
>      def get_all_market_tickers(self):
I'm wondering if these tickers could and should be implemented as in https://github.com/edeng23/binance-trade-bot/pull/205 with the cached fees.

2021-03-14 23:48 UTC, Pekafu commented on binance_trade_bot/binance_api_manager.py
> +        self.bm.start()
After implementing these closing the program should be done as introduced here: https://python-binance.readthedocs.io/en/latest/websockets.html#close-and-exit-program

I've been experimenting with it and it seems we could actually do it here: https://github.com/edeng23/binance-trade-bot/blob/7e1f72c80d1e6ef05249baff865c1df6c2e1a095/binance_trade_bot/crypto_trading.py#L36
some what like this:

    try:
        while True:
            schedule.run_pending()
            time.sleep(1)
        finally:
            manager.bm.close()
            reactor.stop()

2021-03-14 23:48 UTC, Pekafu commented on binance_trade_bot/binance_api_manager.py
> +        self.bm.start_all_mark_price_socket(self._process_all_mark_price_socket)
starting socket might be worth doing in it's own function e.g.

    def start_all_price_socket(self):
        conn = self.bm.start_all_mark_price_socket(self._process_all_mark_price_socket)
        if type(conn) == bool and conn == False
             self.logger.log("Starting all mark price socket failed, retrying")
             # call retry here
        else:
            self.all_price_socket_conn_key = conn

2021-03-15 01:04 UTC, ryansonshine commented on binance_trade_bot/binance_api_manager.py
>      def get_all_market_tickers(self):
Did you intend to reference a different PR? I'm not sure I understand.

2021-03-15 08:48 UTC, Pekafu commented on binance_trade_bot/binance_api_manager.py
>      def get_all_market_tickers(self):
Fixed

2021-03-15 12:22 UTC, j-waters commented on binance_trade_bot/binance_api_manager.py
>      def get_all_market_tickers(self):
If you mean replace `get_all_market_tickers` with calls to `get_market_ticker_price` every time I agree

2021-03-16 21:53 UTC, j-waters commented
I continued this PR in https://github.com/edeng23/binance-trade-bot/pull/211, I hope that's okay! Your work was a great foundation!

2021-03-16 22:11 UTC, ryansonshine commented
@j-waters Sounds good to me! Thanks

2021-03-16 22:11 UTC, closed without merging