Make fee automation configurable
ccxt/binance-trade-bot pull request #208
Opened 2021-03-16 09:15 UTC by Pekafu

2021-03-16 09:18 UTC, Pekafu commented
I'll fix linting in minute and will add mention to the readme

2021-03-16 09:47 UTC, j-waters commented
I'd say instead of giving the user those 3 options, maybe just give them the option between `auto` and a number. Then in the README we give a link to the default binance fees

2021-03-16 12:47 UTC, j-waters commented on binance_trade_bot/binance_api_manager.py
> +        if self.TRADE_FEE:
Why not do 
```suggestion
        if self.config.TRADE_FEE == 'auto':
            ...
        else:
            return float(self.config.TRADE_FEE)
```

We don't have any other configuration in the `__init__` method and I think we should keep it that way

2021-03-16 12:51 UTC, Pekafu commented on binance_trade_bot/binance_api_manager.py
> +        if self.TRADE_FEE:
true, yet binance_api_manager doesn't have config itself. Need to use self.binance_client.config.TRADE_FEE

2021-03-16 12:52 UTC, Pekafu commented on binance_trade_bot/binance_api_manager.py
> +        if self.TRADE_FEE:
True, yet binance_api_manager doesn't store config

2021-03-16 15:09 UTC, j-waters commented on binance_trade_bot/binance_api_manager.py
> +        if self.TRADE_FEE:
I'd make it store the config then. I know another PR has also done that.

2021-03-16 22:33 UTC, Pekafu commented
After merging #211 this isn't as nessessary as before

2021-03-17 06:08 UTC, rel-s commented
> 
> 
> After merging #211 this isn't as nessessary as before

@Pekafu how so?

2021-03-17 06:10 UTC, Pekafu commented
Api call weight won't be exceeded as easily as currently

2021-03-19 07:54 UTC, edeng23 commented
I think that it's a good idea to have this optionality regardless of #211.

2021-03-20 17:47 UTC, Blaklis commented
Considering the US tld seems to return an empty list, this PR would fix a blocker for them, as it currently crashed trying to retrieve the fees for specific pairs.

2021-03-23 04:48 UTC, edeng23 commented
@Pekafu Can you please rebase?

2021-03-23 09:02 UTC, Pekafu commented
@edeng23 rebased

2021-04-16 04:00 UTC, yudataguy commented
Hope this get merged soon, implemented the code to get the binance.us `trade_fee` issue sorted out finally

2021-05-11 15:26 UTC, rel-s requested changes
Totally forgot about this, sorry...
I think that before merging we should add the new `trade_fee` option to `.user.cfg.example`, as we did with previous config changes. Other than that, nothing to add :)

2026-07-18 18:36 UTC, closed without merging