(docs) update README.md
ccxt/binance-trade-bot pull request #213
Opened 2021-03-18 06:54 UTC by vladdoster

- Update wording
- provide relevant links
- make the FAQ image smaller
- make disclaimer clearer
- wrap lines to make it easier to read from CLI

2021-03-18 09:35 UTC, GrigorovskyA requested changes

2021-03-18 09:35 UTC, GrigorovskyA commented on README.md
> +export scout_multiplier=5
Code using other ENV variables. You can find it there - https://github.com/edeng23/binance-trade-bot/blob/master/binance_trade_bot/config.py

2021-03-18 12:37 UTC, Pekafu commented on README.md
> +1. Ensure that you have enough BNB in your account to pay the fee of the
```suggestion
2. Ensure that you have enough BNB in your account to pay the fee of the
```

2021-03-18 12:37 UTC, Pekafu commented on README.md
> +1. Take into consideration the discount when calculating the trading threshold.
```suggestion
3. Take into consideration the discount when calculating the trading threshold.
```

2021-03-19 08:41 UTC, edeng23 commented
Why are all of the lines marked as modified and not only the ones you've changed?

2021-03-19 10:21 UTC, edeng23 commented
I think that line wrapping should be enforced as a linting rule in order to avoid future inconsistencies.

2021-03-19 10:23 UTC, edeng23 requested changes

2021-03-19 10:23 UTC, edeng23 commented on README.md
> +  <img src="https://usercontent2.hubstatic.com/6061829.jpg" width="500" height="500">
The aspect ratio should be corrected, these dimensions stretch the image.

2021-03-21 21:27 UTC, edeng23 commented
I'll close this PR now and make some changes to the README. I really appreciate the work you put in, and am only taking over because I think that it's important to update the outdated information as soon as possible.

2021-03-21 21:28 UTC, closed without merging

2021-03-22 13:40 UTC, 77mena reviewed
Hello...im really sorry wont happen agine