Allow 2 active coins to be traded
ccxt/binance-trade-bot pull request #317
Opened 2021-05-04 10:29 UTC by laffy

The version will split your USDT balance and trade on 2 coins at any one time.

It will not allow you to buy an active coin with the second bot, thereby distributing your trading and risk.

I am running this on production now, I will let you know how it works out.

2021-05-04 10:46 UTC, laffy commented on binance_trade_bot/database.py
> +            self.send_update(bought_coin)
For some reason this creates an error, likely from flushing the session, however it does not prevent the bot from continuing to run.

I could not find another way to update active coins within the bot thread, perhaps somebody who knows more about Python than me can help?

![image](https://user-images.githubusercontent.com/441219/116992458-f1cdc680-accd-11eb-9fa7-76f89c174ea6.png)

2021-05-04 11:49 UTC, j-waters requested changes
This was one of the main reasons I created the multiple coins strategy in the first place, so thank you so much for putting this together!

A couple of thoughts (feel free to disagree):
* I think this should be generalised to allow for more than 2 coins to be active, is there a reason why it's limited to 2?
* I'm pretty cautious about adding a new row to the database, although an 'active' column is a fairly good idea and could even replace the `current_coin` table as a more robust alternative (especially as more strategies are added), would have to get @edeng23's opinion on that. The real issue is you need to have a system for migration - if your PR was merged, people would have to delete their database to use the new version, which obviously isn't ideal. Now, a migration system is way beyond the scope of this PR, so I don't suggest you add one, it just means that as it stands this is unlikely to be merged. Would it be possible to simply infer which coins are active by which coins the user owns? So if I have ETH and XLM and nothing else, we assume those are my 'active coins'? It might not be ideal but it would mean this could be merged
* There has been some discussion previously about configuring strategies, and that we should have different sections in the config file for different strategies, or separate config files entirely. Not sure what the best solution is, this is just the first PR to add a new strategy so we might want to  discuss it

2021-05-04 11:49 UTC, j-waters commented on .user.cfg.example
> +api_key=XXX
That API key is the example they use on the API documentation no need to change it

2021-05-04 11:49 UTC, j-waters commented on binance_trade_bot/auto_trader.py
>              self.db.set_current_coin(pair.to_coin)
There's some debate about whether this will remain, I don't think you need to worry - it might be removed at some point (in my opinion this class shouldn't have any references to 'current_coin')

2021-05-04 11:49 UTC, j-waters commented on binance_trade_bot/auto_trader.py
> +            for active_coin in self.db.get_active_coins():
Instead I would add an optional `excluded_coins` argument to some of these methods - ideally, the `AutoTrader` class shouldn't have stuff that is only really used by one strategy

2021-05-04 11:49 UTC, j-waters commented on binance_trade_bot/auto_trader.py
>      def bridge_scout(self):
```suggestion
    def bridge_scout(self, excluded_coins=None):
        if excluded_coins is None:
            excluded_coins = []
```

See my previous comment

2021-05-04 11:49 UTC, j-waters commented on binance_trade_bot/database.py
> +# TODO: Can I move this out to a model class?
I don't think so since this isn't a database model per se - the actually model is `Trade`, this is just a wrapper that facilitates changing the actual database model

2021-05-04 11:49 UTC, j-waters commented on binance_trade_bot/strategies/multiple_active_coins_strategy.py
> +from datetime import datetime
If you wanted to add this to the existing multiple_coins_strategy I don't think that would be an issue

2021-05-04 11:50 UTC, j-waters commented on binance_trade_bot/database.py
> +# TODO: Can I move this out to a model class?
Also that's out of the scope of this PR

2021-05-04 13:37 UTC, laffy commented
Hi @j-waters thanks for your comments.

I should have made this a draft PR that is my mistake sorry, it's definitely not ready to be merged yet as I know I haven't separated out the concerns fully yet.

I will full review your feedback this evening.

2021-05-04 13:41 UTC, laffy commented on binance_trade_bot/strategies/multiple_active_coins_strategy.py
> +from datetime import datetime
Ah yes, I needed this as my `production` version runs on Postgres not SQLite.

2021-05-04 13:42 UTC, laffy commented on binance_trade_bot/strategies/multiple_active_coins_strategy.py
> +from datetime import datetime
It already is: 

https://github.com/edeng23/binance-trade-bot/blob/master/binance_trade_bot/strategies/multiple_coins_strategy.py#L1

2021-05-04 15:11 UTC, j-waters commented on binance_trade_bot/strategies/multiple_active_coins_strategy.py
> +from datetime import datetime
Oh weird sorry on Github it looks like this is a brand new file rather than a modified one

2021-05-06 14:27 UTC, laffy commented on .user.cfg.example
> +api_key=XXX
I think they should be removed from the example file completely to prevent somebody accidentally sending their real API keys to somebody else.

2021-05-06 14:40 UTC, laffy commented
@j-waters I have addressed your first point. It was set to 2 mostly to confirm it worked. I have now made this a variable and tested it, so this can be set to any number you want now.

2021-05-08 23:51 UTC, Nesonica commented
Hi there, thanks for the commit! How can I pull this into my current Pycharm Project? :-)

2021-05-10 22:08 UTC, erenatas commented on .user.cfg.example
> +api_key=XXX
User should never send someone his/her user.cfg directly. That's user's fault and not related to this PR.

2021-05-16 18:54 UTC, laffy commented on binance_trade_bot/database.py
> +            self.send_update(bought_coin)
Can anybody help with this error?

2021-05-16 18:54 UTC, laffy commented on .user.cfg.example
> +api_key=XXX
That is true, but why even risk it? :)

2021-05-16 18:55 UTC, laffy commented on README.md
> +SELL_ORDER_TYPE: market
TODO: Add to readme.

2021-05-19 15:41 UTC, laffy commented
Too out of sync now. Not going to work on this anymore.

2021-05-19 15:41 UTC, closed without merging

2021-06-11 07:36 UTC, 556isback commented
I am wondering if I could have your permission to implement your code on #361, It could really help with the conflict of my modification and the multiple coin strategy.