Margin
ccxt/binance-trade-bot pull request #417
Opened 2021-09-08 02:48 UTC by bamooxa

Better core formula.
I've been running for some months now and I haven't come across the instant/unnecessary trade bug (A>B>C instantly).
Every trade results in atleast my scout margin percentage coin profit.

2021-09-08 17:07 UTC, edeng23 commented
I like this change, it makes more sense than my original formula. Will run a few tests and hopefully merge soon.

2021-09-16 21:43 UTC, yigitakbulut requested changes
Very good! Thank you for this, I think the strategy works better with this.
There is a typo in auto_trader.py, also you should convert the scout margin to float when you import it from config.

2021-09-16 21:43 UTC, yigitakbulut commented on binance_trade_bot/auto_trader.py
> +                    (1- transaction_fee) * coin_opt_coin_ratio / pair.ratio - 1 - self.CONFIG.SCOUT_MARGIN / 100
Here it should be self.**config**.SCOUT_MARGIN

2021-09-16 21:43 UTC, yigitakbulut commented on binance_trade_bot/config.py
> +        self.SCOUT_MARGIN = os.environ.get("SCOUT_MARGIN") or config.get(USER_CFG_SECTION, "scout_margin")
self.SCOUT_MARGIN = **float(** os.environ.get("SCOUT_MARGIN") or config.get(USER_CFG_SECTION, "scout_margin")**)**

2021-09-18 15:33 UTC, yigitakbulut approved these changes

2021-10-09 21:21 UTC, lisabbasil commented
I'm a bit confused about the fees. They are given as a percentage, so should be multiplied with the volume that will be traded, not with a ratio, or a ratio of ratios. Guess I just don't understand the formula?

2021-10-11 10:04 UTC, rogerthomas84 commented
I really like this proposed change 👍

2021-11-03 09:24 UTC, muhammadnumair commented
Thanks for the change, @edeng23 were you able to test it?

2021-11-13 10:33 UTC, merged